In [44]:
import pandas as pd
import numpy as np
import matplotlib as plt
%matplotlib inline

In [31]:
train_df = pd.read_csv("D:/py_fi/titanic/train.csv")
test_df = pd.read_csv("D:/py_fi/titanic/test.csv")


In [33]:
train_df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [34]:
train_df.set_index('PassengerId', inplace = True)
test_df.set_index("PassengerId",inplace = True)

In [35]:
train_df.head()

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   

             SibSp  Parch            Ticket     Fare Cabin Embarked  
PassengerId                                                          
1                1      0         A/5 21171   7.2500   NaN        S  
2                1      0          PC 17599  71.2833   C85        C  
3                0      0  STON/O2. 3101282   7.9250   NaN        S  
4                1      0            113803  53.1000  C123        S  
5                0      0            373450   8.0500   NaN        S

In [36]:
train_index = train_df.index
test_index = test_df.index

In [37]:
y_train_df = train_df.pop("Survived")

In [38]:
y_train_df.head()

PassengerId
1    0
2    1
3    1
4    1
5    0
Name: Survived, dtype: int64

## Data Preproecessing

In [39]:
#플로팅을 소수점 두자리까지만 보여줌
pd.set_option('display.float_format', lambda x : '%.2f' %x)

In [48]:
test_df.isnull().sum() / len(test_df)

Pclass     0.00
Name       0.00
Sex        0.00
Age        0.21
SibSp      0.00
Parch      0.00
Ticket     0.00
Fare       0.00
Cabin      0.78
Embarked   0.00
dtype: float64

In [49]:
test_df.isnull().sum() / len(test_df) * 100

Pclass      0.00
Name        0.00
Sex         0.00
Age        20.57
SibSp       0.00
Parch       0.00
Ticket      0.00
Fare        0.24
Cabin      78.23
Embarked    0.00
dtype: float64

In [50]:
del train_df["Cabin"]
del test_df["Cabin"]

In [52]:
all_df = train_df.append(test_df)
all_df

Pclass                                               Name  \
PassengerId                                                              
1                 3                            Braund, Mr. Owen Harris   
2                 1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
3                 3                             Heikkinen, Miss. Laina   
4                 1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
5                 3                           Allen, Mr. William Henry   
6                 3                                   Moran, Mr. James   
7                 1                            McCarthy, Mr. Timothy J   
8                 3                     Palsson, Master. Gosta Leonard   
9                 3  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)   
10                2                Nasser, Mrs. Nicholas (Adele Achem)   
11                3                    Sandstrom, Miss. Marguerite Rut   
12                1                           Bonnell, Miss. Elizabeth   
13                3                     Saundercock, Mr. William Henry   
14                3                        Andersson, Mr. Anders Johan   
15                3               Vestrom, Miss. Hulda Amanda Adolfina   
16                2                   Hewlett, Mrs. (Mary D Kingcome)    
17                3                               Rice, Master. Eugene   
18                2                       Williams, Mr. Charles Eugene   
19                3  Vander Planke, Mrs. Julius (Emelia Maria Vande...   
20                3                            Masselmani, Mrs. Fatima   
21                2                               Fynney, Mr. Joseph J   
22                2                              Beesley, Mr. Lawrence   
23                3                        McGowan, Miss. Anna "Annie"   
24                1                       Sloper, Mr. William Thompson   
25                3                      Palsson, Miss. Torborg Danira   
26                3  Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...   
27                3                            Emir, Mr. Farred Chehab   
28                1                     Fortune, Mr. Charles Alexander   
29                3                      O'Dwyer, Miss. Ellen "Nellie"   
30                3                                Todoroff, Mr. Lalio   
...             ...                                                ...   
1280              3                               Canavan, Mr. Patrick   
1281              3                        Palsson, Master. Paul Folke   
1282              1                         Payne, Mr. Vivian Ponsonby   
1283              1     Lines, Mrs. Ernest H (Elizabeth Lindsey James)   
1284              3                      Abbott, Master. Eugene Joseph   
1285              2                               Gilbert, Mr. William   
1286              3                           Kink-Heilmann, Mr. Anton   
1287              1     Smith, Mrs. Lucien Philip (Mary Eloise Hughes)   
1288              3                               Colbert, Mr. Patrick   
1289              1  Frolicher-Stehli, Mrs. Maxmillian (Margaretha ...   
1290              3                     Larsson-Rondberg, Mr. Edvard A   
1291              3                           Conlon, Mr. Thomas Henry   
1292              1                            Bonnell, Miss. Caroline   
1293              2                                    Gale, Mr. Harry   
1294              1                     Gibson, Miss. Dorothy Winifred   
1295              1                             Carrau, Mr. Jose Pedro   
1296              1                       Frauenthal, Mr. Isaac Gerald   
1297              2       Nourney, Mr. Alfred (Baron von Drachstedt")"   
1298              2                          Ware, Mr. William Jeffery   
1299              1                         Widener, Mr. George Dunton   
1300              3                    Riordan, Miss. Johanna Hannah""   
1301             

In [53]:
all_df.isnull().sum() / len(all_df) * 100

Pclass      0.00
Name        0.00
Sex         0.00
Age        20.09
SibSp       0.00
Parch       0.00
Ticket      0.00
Fare        0.08
Embarked    0.15
dtype: float64

In [55]:
del all_df["Name"]
del all_df["Ticket"]

In [56]:
all_df.head()

Pclass     Sex   Age  SibSp  Parch  Fare Embarked
PassengerId                                                   
1                 3    male 22.00      1      0  7.25        S
2                 1  female 38.00      1      0 71.28        C
3                 3  female 26.00      0      0  7.92        S
4                 1  female 35.00      1      0 53.10        S
5                 3    male 35.00      0      0  8.05        S

In [57]:
all_df["Sex"] = all_df["Sex"].replace({"male":0,"female":1})
all_df.head()

Pclass  Sex   Age  SibSp  Parch  Fare Embarked
PassengerId                                                
1                 3    0 22.00      1      0  7.25        S
2                 1    1 38.00      1      0 71.28        C
3                 3    1 26.00      0      0  7.92        S
4                 1    1 35.00      1      0 53.10        S
5                 3    0 35.00      0      0  8.05        S

In [58]:
all_df["Embarked"].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [59]:
all_df["Embarked"] = all_df["Embarked"].replace({"S":0,"C":1,"Q":2,np.nan:99})

In [60]:
all_df["Embarked"].unique()

array([ 0,  1,  2, 99], dtype=int64)

In [61]:
pd.get_dummies(all_df["Embarked"],prefix = "embarked")

embarked_0  embarked_1  embarked_2  embarked_99
PassengerId                                                 
1                     1           0           0            0
2                     0           1           0            0
3                     1           0           0            0
4                     1           0           0            0
5                     1           0           0            0
6                     0           0           1            0
7                     1           0           0            0
8                     1           0           0            0
9                     1           0           0            0
10                    0           1           0            0
11                    1           0           0            0
12                    1           0           0            0
13                    1           0           0            0
14                    1           0           0            0
15                    1           0           0            0
16                    1           0           0            0
17                    0           0           1            0
18                    1           0           0            0
19                    1           0           0            0
20                    0           1           0            0
21                    1           0           0            0
22                    1           0           0            0
23                    0           0           1            0
24                    1           0           0            0
25                    1           0           0            0
26                    1           0           0            0
27                    0           1           0            0
28                    1           0           0            0
29                    0           0           1            0
30                    1           0           0            0
...                 ...         ...         ...          ...
1280                  0           0           1            0
1281                  1           0           0            0
1282                  1           0           0            0
1283                  1           0           0            0
1284                  1           0           0            0
1285                  1           0           0            0
1286                  1           0           0            0
1287                  1           0           0            0
1288                  0           0           1            0
1289                  0           1           0            0
1290                  1           0           0            0
1291                  0           0           1            0
1292                  1           0           0            0
1293                  1           0           0            0
1294                  0           1           0            0
1295                  1           0           0            0
1296                  0           1           0            0
1297                  0           1           0            0
1298                  1           0           0            0
1299                  0           1           0            0
1300                  0           0           1            0
1301                  1           0           0            0
1302                  0           0           1            0
1303                  0           0           1            0
1304                  1           0           0            0
1305                  1           0           0            0
1306                  0           1           0            0
1307                  1           0           0            0
1308                  1           0           0            0
1309                  0           1           0            0

[1309 rows x 4 columns]

In [62]:
matrix_df = pd.merge(all_df, pd.get_dummies(all_df["Embarked"],prefix = "embarked"), left_index = True, right_index=True)
matrix_df.head()

Pclass  Sex   Age  SibSp  Parch  Fare  Embarked  embarked_0  \
PassengerId                                                                
1                 3    0 22.00      1      0  7.25         0           1   
2                 1    1 38.00      1      0 71.28         1           0   
3                 3    1 26.00      0      0  7.92         0           1   
4                 1    1 35.00      1      0 53.10         0           1   
5                 3    0 35.00      0      0  8.05         0           1   

             embarked_1  embarked_2  embarked_99  
PassengerId                                       
1                     0           0            0  
2                     1           0            0  
3                     0           0            0  
4                     0           0            0  
5                     0           0            0

In [63]:
matrix_df.corr()
#상관관계 분석

Pclass   Sex   Age  SibSp  Parch  Fare  Embarked  embarked_0  \
Pclass         1.00 -0.12 -0.41   0.06   0.02 -0.56     -0.05        0.10   
Sex           -0.12  1.00 -0.06   0.11   0.21  0.19      0.07       -0.12   
Age           -0.41 -0.06  1.00  -0.24  -0.15  0.18      0.07       -0.08   
SibSp          0.06  0.11 -0.24   1.00   0.37  0.16     -0.03        0.08   
Parch          0.02  0.21 -0.15   0.37   1.00  0.22     -0.03        0.07   
Fare          -0.56  0.19  0.18   0.16   0.22  1.00      0.05       -0.17   
Embarked      -0.05  0.07  0.07  -0.03  -0.03  0.05      1.00       -0.21   
embarked_0     0.10 -0.12 -0.08   0.08   0.07 -0.17     -0.21        1.00   
embarked_1    -0.27  0.07  0.09  -0.05  -0.01  0.29      0.06       -0.78   
embarked_2     0.23  0.09 -0.02  -0.05  -0.10 -0.13      0.12       -0.49   
embarked_99   -0.06  0.05  0.06  -0.02  -0.02  0.04      0.99       -0.06   

             embarked_1  embarked_2  embarked_99  
Pclass            -0.27        0.23        -0.06  
Sex                0.07        0.09         0.05  
Age                0.09       -0.02         0.06  
SibSp             -0.05       -0.05        -0.02  
Parch             -0.01       -0.10        -0.02  
Fare               0.29       -0.13         0.04  
Embarked           0.06        0.12         0.99  
embarked_0        -0.78       -0.49        -0.06  
embarked_1         1.00       -0.16        -0.02  
embarked_2        -0.16        1.00        -0.01  
embarked_99       -0.02       -0.01         1.00

In [64]:
#그룹함수로 클래스별의 나이 평균을 계산
all_df.groupby("Pclass")["Age"].mean()

Pclass
1   39.16
2   29.51
3   24.82
Name: Age, dtype: float64

In [65]:
#Pclass에 탑승하고 나이가 null값은 사람들을 출력
all_df.loc[ (all_df["Pclass"] == 1) & (all_df["Age"].isnull()) , "Age"]

PassengerId
32     nan
56     nan
65     nan
167    nan
169    nan
186    nan
257    nan
271    nan
285    nan
296    nan
299    nan
307    nan
335    nan
352    nan
376    nan
458    nan
476    nan
508    nan
528    nan
558    nan
603    nan
634    nan
670    nan
712    nan
741    nan
767    nan
794    nan
816    nan
840    nan
850    nan
914    nan
933    nan
1038   nan
1040   nan
1060   nan
1083   nan
1097   nan
1158   nan
1182   nan
Name: Age, dtype: float64

In [66]:
#결측치를 평균값으로 대체
all_df.loc[(all_df["Pclass"] == 1) & (
        all_df["Age"].isnull()), "Age"] = 39.16
all_df.loc[ (
    all_df["Pclass"] == 2) & all_df["Age"].isnull() , "Age"] = 29.51
all_df.loc[ ( all_df["Pclass"] == 3) & all_df["Age"].isnull(), "Age"] = 24.82

In [67]:
all_df.isnull().sum()

Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        1
Embarked    0
dtype: int64

In [68]:
#클래스별 Fare의 평균계산 
all_df.groupby("Pclass")["Fare"].mean()

Pclass
1   87.51
2   21.18
3   13.30
Name: Fare, dtype: float64

In [69]:
all_df[all_df["Fare"].isnull()]

Pclass  Sex   Age  SibSp  Parch  Fare  Embarked
PassengerId                                                 
1044              3    0 60.50      0      0   nan         0

In [70]:
all_df.loc[all_df["Fare"].isnull(), "Fare"] = 13.30

In [71]:
del all_df["Embarked"]

In [72]:
all_df.head()

Pclass  Sex   Age  SibSp  Parch  Fare
PassengerId                                       
1                 3    0 22.00      1      0  7.25
2                 1    1 38.00      1      0 71.28
3                 3    1 26.00      0      0  7.92
4                 1    1 35.00      1      0 53.10
5                 3    0 35.00      0      0  8.05

In [73]:
all_df["Pclass"] = all_df["Pclass"].replace({1:"A",2:"B",3:"C"})

In [74]:
all_df.head()

Pclass  Sex   Age  SibSp  Parch  Fare
PassengerId                                      
1                C    0 22.00      1      0  7.25
2                A    1 38.00      1      0 71.28
3                C    1 26.00      0      0  7.92
4                A    1 35.00      1      0 53.10
5                C    0 35.00      0      0  8.05

In [76]:
all_df = pd.get_dummies(all_df)
all_df.head()

Sex   Age  SibSp  Parch  Fare  Pclass_A  Pclass_B  Pclass_C
PassengerId                                                             
1              0 22.00      1      0  7.25         0         0         1
2              1 38.00      1      0 71.28         1         0         0
3              1 26.00      0      0  7.92         0         0         1
4              1 35.00      1      0 53.10         1         0         0
5              0 35.00      0      0  8.05         0         0         1

In [78]:
all_df = pd.merge(all_df,
                  matrix_df[["embarked_0","embarked_1","embarked_2","embarked_99"]],
                 left_index = True, right_index = True)

In [79]:
all_df.head()

Sex   Age  SibSp  Parch  Fare  Pclass_A  Pclass_B  Pclass_C  \
PassengerId                                                                
1              0 22.00      1      0  7.25         0         0         1   
2              1 38.00      1      0 71.28         1         0         0   
3              1 26.00      0      0  7.92         0         0         1   
4              1 35.00      1      0 53.10         1         0         0   
5              0 35.00      0      0  8.05         0         0         1   

             embarked_0  embarked_1  embarked_2  embarked_99  
PassengerId                                                   
1                     1           0           0            0  
2                     0           1           0            0  
3                     1           0           0            0  
4                     1           0           0            0  
5                     1           0           0            0

In [80]:
train_df = all_df[all_df.index.isin(train_index)]
test_df = all_df[all_df.index.isin(test_index)]

In [83]:
train_df.head()
test_df.head()

Sex   Age  SibSp  Parch  Fare  Pclass_A  Pclass_B  Pclass_C  \
PassengerId                                                                
892            0 34.50      0      0  7.83         0         0         1   
893            1 47.00      1      0  7.00         0         0         1   
894            0 62.00      0      0  9.69         0         1         0   
895            0 27.00      0      0  8.66         0         0         1   
896            1 22.00      1      1 12.29         0         0         1   

             embarked_0  embarked_1  embarked_2  embarked_99  
PassengerId                                                   
892                   0           0           1            0  
893                   1           0           0            0  
894                   0           0           1            0  
895                   1           0           0            0  
896                   1           0           0            0

# Build Model

In [85]:
x_data = train_df.as_matrix()
y_data = y_train_df.as_matrix()

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


In [86]:
x_data.shape, y_data.shape

((891, 12), (891,))

In [87]:
y_data

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,

In [88]:
from sklearn.linear_model import LogisticRegression 
cls = LogisticRegression()
cls.fit(x_data,y_data)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [89]:
cls.intercept_

array([0.18829674])

In [90]:
cls.coef_

array([[ 2.60750665e+00, -4.07586678e-02, -3.25647165e-01,
        -8.49180077e-02,  2.48637600e-03,  1.11465026e+00,
         1.52999437e-01, -1.07935295e+00, -2.45258166e-01,
         1.66095755e-01,  6.65916090e-02,  2.00867547e-01]])

In [91]:
cls.predict(test_df.values)

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [92]:
test_df.index

Int64Index([ 892,  893,  894,  895,  896,  897,  898,  899,  900,  901,
            ...
            1300, 1301, 1302, 1303, 1304, 1305, 1306, 1307, 1308, 1309],
           dtype='int64', name='PassengerId', length=418)

In [94]:
x_test = test_df.as_matrix()
y_test = cls.predict(x_test)
y_test

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [95]:
result = np.concatenate((test_index.values.reshape(-1,1),
                        cls.predict(x_test).reshape(-1,1)),axis = 1)
result[:5]

array([[892,   0],
       [893,   0],
       [894,   0],
       [895,   0],
       [896,   1]], dtype=int64)

In [97]:
df_submission = pd.DataFrame(result, columns=["PassengerId","Survived"])
df_submission

PassengerId  Survived
0            892         0
1            893         0
2            894         0
3            895         0
4            896         1
5            897         0
6            898         1
7            899         0
8            900         1
9            901         0
10           902         0
11           903         0
12           904         1
13           905         0
14           906         1
15           907         1
16           908         0
17           909         0
18           910         1
19           911         1
20           912         0
21           913         0
22           914         1
23           915         1
24           916         1
25           917         0
26           918         1
27           919         0
28           920         0
29           921         0
..           ...       ...
388         1280         0
389         1281         0
390         1282         1
391         1283         1
392         1284         0
393         1285         0
394         1286         0
395         1287         1
396         1288         0
397         1289         1
398         1290         0
399         1291         0
400         1292         1
401         1293         0
402         1294         1
403         1295         1
404         1296         0
405         1297         0
406         1298         0
407         1299         0
408         1300         1
409         1301         1
410         1302         1
411         1303         1
412         1304         1
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [99]:
df_submission.to_csv("submission_result.csv",index=False)